# Generated by Django 4.1.6 on 2023-02-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(unique=True, verbose_name='Зав. № машины')),
                ('engine_serial_number', models.TextField(verbose_name='Зав. № двигателя')),
                ('transmission_serial_number', models.TextField(verbose_name='Зав. № трансмиссии')),
                ('driving_axle_serial_number', models.TextField(verbose_name='Зав. № ведущего моста')),
                ('steering_axle_serial_number', models.TextField(verbose_name='Зав. № управляемого моста')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.TextField(verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_adress', models.TextField(verbose_name='Адрес поставки (эксплуатации)')),
                ('additional_equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='Maitenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('contract_serial_number', models.TextField(unique=True, verbose_name='№ заказ-наряда')),
                ('contract_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('self_maitenance', models.BooleanField(default=False, verbose_name='Самостоятельное проведение ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('description', models.TextField(verbose_name='Описание отказа')),
                ('repair_parts', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('repair_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='Время простоя техники')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car', verbose_name='Машина')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manuals.repairmethod', verbose_name='Способ восстановления')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['issue_date'],
            },
        ),
    ]
