# Generated by Django 4.1.6 on 2023-02-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuals', '0001_initial'),
        ('users', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='repair',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manuals.repairunit', verbose_name='Узел отказа'),
        ),
        migrations.AddField(
            model_name='maitenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car', verbose_name='Зав. № машины'),
        ),
        migrations.AddField(
            model_name='maitenance',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.maitenanceprovider', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AddField(
            model_name='maitenance',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maitenance_service_company', to='users.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='maitenance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.maitenancetype', verbose_name='Вид ТО'),
        ),
        migrations.AddField(
            model_name='car',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='car',
            name='driving_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.drivingaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.carmodel', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='car',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.steeringaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuals.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
